name: Build
on:
  push:
    branches:
      - 'asm/testing'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install QEMU
        run: sudo apt install qemu-user-static
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@default
        with:
          version: 0.9.0
      - name: Environment
        run: qemu-arm-static --version && zig --version && bison --version && flex --version
      - name: Build
        run: bash build.sh
      - name: Test
        run: bash test.sh -c
      #- uses: actions/upload-artifact@v3
        #with:
          #name: ignore-${{ matrix.target }}
          #path: a.out
